inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Style/Documentation:
  Enabled: false

Metrics/BlockLength: 
  AllowedMethods: ['describe', 'context']
  Exclude:
   - lib/tasks/dev.rake

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/FilePath:
  Enabled: false